// Package bannerify provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package bannerify

const (
	TokenScopes = "token.Scopes"
)

// Defines values for ErrBadRequestErrorCode.
const (
	BADREQUEST ErrBadRequestErrorCode = "BAD_REQUEST"
)

// Defines values for ErrConflictErrorCode.
const (
	CONFLICT ErrConflictErrorCode = "CONFLICT"
)

// Defines values for ErrFetchImageErrorErrorCode.
const (
	FETCHIMAGEERROR ErrFetchImageErrorErrorCode = "FETCH_IMAGE_ERROR"
)

// Defines values for ErrForbiddenErrorCode.
const (
	FORBIDDEN ErrForbiddenErrorCode = "FORBIDDEN"
)

// Defines values for ErrInternalServerErrorErrorCode.
const (
	INTERNALSERVERERROR ErrInternalServerErrorErrorCode = "INTERNAL_SERVER_ERROR"
)

// Defines values for ErrNotFoundErrorCode.
const (
	NOTFOUND ErrNotFoundErrorCode = "NOT_FOUND"
)

// Defines values for ErrTooManyRequestsErrorCode.
const (
	TOOMANYREQUESTS ErrTooManyRequestsErrorCode = "TOO_MANY_REQUESTS"
)

// Defines values for ErrUnauthorizedErrorCode.
const (
	UNAUTHORIZED ErrUnauthorizedErrorCode = "UNAUTHORIZED"
)

// Defines values for ModificationHeightMode.
const (
	ModificationHeightModeAdaptive ModificationHeightMode = "adaptive"
	ModificationHeightModeStandard ModificationHeightMode = "standard"
)

// Defines values for ModificationTheme.
const (
	ARCO     ModificationTheme = "ARCO"
	BRIGHT   ModificationTheme = "BRIGHT"
	DEFAULT  ModificationTheme = "DEFAULT"
	NONE     ModificationTheme = "NONE"
	SIMPLIFY ModificationTheme = "SIMPLIFY"
)

// Defines values for ModificationWidthMode.
const (
	ModificationWidthModeAdaptive ModificationWidthMode = "adaptive"
	ModificationWidthModeStandard ModificationWidthMode = "standard"
)

// Defines values for PostV1TemplatesCreateImageJSONBodyFormat.
const (
	PostV1TemplatesCreateImageJSONBodyFormatJpeg PostV1TemplatesCreateImageJSONBodyFormat = "jpeg"
	PostV1TemplatesCreateImageJSONBodyFormatPng  PostV1TemplatesCreateImageJSONBodyFormat = "png"
	PostV1TemplatesCreateImageJSONBodyFormatWebp PostV1TemplatesCreateImageJSONBodyFormat = "webp"
)

// Defines values for PostV1TemplatesCreateStoredImageJSONBodyFormat.
const (
	PostV1TemplatesCreateStoredImageJSONBodyFormatJpeg PostV1TemplatesCreateStoredImageJSONBodyFormat = "jpeg"
	PostV1TemplatesCreateStoredImageJSONBodyFormatPng  PostV1TemplatesCreateStoredImageJSONBodyFormat = "png"
	PostV1TemplatesCreateStoredImageJSONBodyFormatWebp PostV1TemplatesCreateStoredImageJSONBodyFormat = "webp"
)

// Defines values for GetV1TemplatesSignedurlParamsFormat.
const (
	Jpeg GetV1TemplatesSignedurlParamsFormat = "jpeg"
	Png  GetV1TemplatesSignedurlParamsFormat = "png"
	Webp GetV1TemplatesSignedurlParamsFormat = "webp"
)

// ErrBadRequest defines model for ErrBadRequest.
type ErrBadRequest struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrBadRequestErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrBadRequestErrorCode A machine readable error code.
type ErrBadRequestErrorCode string

// ErrConflict defines model for ErrConflict.
type ErrConflict struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrConflictErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrConflictErrorCode A machine readable error code.
type ErrConflictErrorCode string

// ErrFetchImageError defines model for ErrFetchImageError.
type ErrFetchImageError struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrFetchImageErrorErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrFetchImageErrorErrorCode A machine readable error code.
type ErrFetchImageErrorErrorCode string

// ErrForbidden defines model for ErrForbidden.
type ErrForbidden struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrForbiddenErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrForbiddenErrorCode A machine readable error code.
type ErrForbiddenErrorCode string

// ErrInternalServerError defines model for ErrInternalServerError.
type ErrInternalServerError struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrInternalServerErrorErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrInternalServerErrorErrorCode A machine readable error code.
type ErrInternalServerErrorErrorCode string

// ErrNotFound defines model for ErrNotFound.
type ErrNotFound struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrNotFoundErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrNotFoundErrorCode A machine readable error code.
type ErrNotFoundErrorCode string

// ErrTooManyRequests defines model for ErrTooManyRequests.
type ErrTooManyRequests struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrTooManyRequestsErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrTooManyRequestsErrorCode A machine readable error code.
type ErrTooManyRequestsErrorCode string

// ErrUnauthorized defines model for ErrUnauthorized.
type ErrUnauthorized struct {
	Error struct {
		// Code A machine readable error code.
		Code ErrUnauthorizedErrorCode `json:"code"`

		// Docs A link to our documentation with more details about this error code
		Docs string `json:"docs"`

		// Message A human readable explanation of what went wrong
		Message string `json:"message"`

		// RequestId Please always include the requestId in your error report
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// ErrUnauthorizedErrorCode A machine readable error code.
type ErrUnauthorizedErrorCode string

// Modification A modification (aka override) to apply to the layer in image
type Modification struct {
	// Barcode Modify the barcode layer content with this field
	Barcode *string `json:"barcode,omitempty"`

	// Chart Update chart layer's data, follow chart.js data structure
	Chart *map[string]*interface{} `json:"chart,omitempty"`

	// Color The color for the modification
	Color *string `json:"color,omitempty"`

	// Columns Table columns
	Columns *[]string `json:"columns,omitempty"`

	// HeightMode Table height mode
	HeightMode *ModificationHeightMode `json:"heightMode,omitempty"`

	// Name The layer name of the modification
	Name string `json:"name"`

	// Qrcode Modify the qrcode layer content with this field
	Qrcode *string `json:"qrcode,omitempty"`

	// Rows Table rows
	Rows *[]interface{} `json:"rows,omitempty"`

	// Src The source image for the modification
	Src *string `json:"src,omitempty"`

	// Star Star value
	Star *float32 `json:"star,omitempty"`

	// Text You can modify the text layer with this field
	Text *string `json:"text,omitempty"`

	// Theme Table theme
	Theme *ModificationTheme `json:"theme,omitempty"`

	// Visible Set the visibility of the field
	Visible *bool `json:"visible,omitempty"`

	// WidthMode Table width mode
	WidthMode *ModificationWidthMode `json:"widthMode,omitempty"`
}

// ModificationHeightMode Table height mode
type ModificationHeightMode string

// ModificationTheme Table theme
type ModificationTheme string

// ModificationWidthMode Table width mode
type ModificationWidthMode string

// GetV1InfoParams defines parameters for GetV1Info.
type GetV1InfoParams struct {
	ApiKey string `form:"apiKey" json:"apiKey"`
}

// GetV1TemplatesParams defines parameters for GetV1Templates.
type GetV1TemplatesParams struct {
	ApiKey        string  `form:"apiKey" json:"apiKey"`
	IncludeLayers *string `form:"includeLayers,omitempty" json:"includeLayers,omitempty"`
}

// GetV1TemplatesIdParams defines parameters for GetV1TemplatesId.
type GetV1TemplatesIdParams struct {
	ApiKey string `form:"apiKey" json:"apiKey"`
}

// PostV1TemplatesCreateImageJSONBody defines parameters for PostV1TemplatesCreateImage.
type PostV1TemplatesCreateImageJSONBody struct {
	// UnderscoreDebug Only for debug purpose, it draws bounding box for each layer
	UnderscoreDebug *string                                   `json:"_debug,omitempty"`
	ApiKey          string                                    `json:"apiKey"`
	Format          *PostV1TemplatesCreateImageJSONBodyFormat `json:"format,omitempty"`
	Modifications   *[]Modification                           `json:"modifications,omitempty"`

	// S3Config Optional custom S3 configuration. If provided, the image will be stored in your S3-compatible storage instead of the default Bannerify storage.
	S3Config *struct {
		// AccessKey S3 access key
		AccessKey string `json:"accessKey"`

		// Bucket S3 bucket name
		Bucket string `json:"bucket"`

		// CustomUrl Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
		CustomUrl *string `json:"customUrl,omitempty"`

		// EndPoint S3 endpoint URL (without protocol)
		EndPoint string `json:"endPoint"`

		// PathStyle Whether to use path-style URLs
		PathStyle *bool `json:"pathStyle,omitempty"`

		// Port S3 endpoint port
		Port *float32 `json:"port,omitempty"`

		// Region S3 region
		Region string `json:"region"`

		// SecretKey S3 secret key
		SecretKey string `json:"secretKey"`

		// UseSSL Whether to use SSL/TLS
		UseSSL *bool `json:"useSSL,omitempty"`
	} `json:"s3Config,omitempty"`

	// TemplateId Your template id
	TemplateId string `json:"templateId"`

	// Thumbnail Generate thumbnail preview (non-billable)
	Thumbnail *bool `json:"thumbnail"`
}

// PostV1TemplatesCreateImageJSONBodyFormat defines parameters for PostV1TemplatesCreateImage.
type PostV1TemplatesCreateImageJSONBodyFormat string

// PostV1TemplatesCreateStoredImageJSONBody defines parameters for PostV1TemplatesCreateStoredImage.
type PostV1TemplatesCreateStoredImageJSONBody struct {
	// UnderscoreDebug Only for debug purpose, it draws bounding box for each layer
	UnderscoreDebug *string                                         `json:"_debug,omitempty"`
	ApiKey          string                                          `json:"apiKey"`
	Format          *PostV1TemplatesCreateStoredImageJSONBodyFormat `json:"format,omitempty"`
	Modifications   *[]Modification                                 `json:"modifications,omitempty"`

	// S3Config Optional custom S3 configuration. If provided, the image will be stored in your S3-compatible storage instead of the default Bannerify storage.
	S3Config *struct {
		// AccessKey S3 access key
		AccessKey string `json:"accessKey"`

		// Bucket S3 bucket name
		Bucket string `json:"bucket"`

		// CustomUrl Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
		CustomUrl *string `json:"customUrl,omitempty"`

		// EndPoint S3 endpoint URL (without protocol)
		EndPoint string `json:"endPoint"`

		// PathStyle Whether to use path-style URLs
		PathStyle *bool `json:"pathStyle,omitempty"`

		// Port S3 endpoint port
		Port *float32 `json:"port,omitempty"`

		// Region S3 region
		Region string `json:"region"`

		// SecretKey S3 secret key
		SecretKey string `json:"secretKey"`

		// UseSSL Whether to use SSL/TLS
		UseSSL *bool `json:"useSSL,omitempty"`
	} `json:"s3Config,omitempty"`

	// TemplateId Your template id
	TemplateId string `json:"templateId"`
}

// PostV1TemplatesCreateStoredImageJSONBodyFormat defines parameters for PostV1TemplatesCreateStoredImage.
type PostV1TemplatesCreateStoredImageJSONBodyFormat string

// GetV1TemplatesSignedurlParams defines parameters for GetV1TemplatesSignedurl.
type GetV1TemplatesSignedurlParams struct {
	Format          *GetV1TemplatesSignedurlParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	Nocache         *string                              `form:"nocache,omitempty" json:"nocache,omitempty"`
	UnderscoreDebug *string                              `form:"_debug,omitempty" json:"_debug,omitempty"`
	S3Config        *struct {
		// AccessKey S3 access key
		AccessKey string `json:"accessKey"`

		// Bucket S3 bucket name
		Bucket string `json:"bucket"`

		// CustomUrl Custom URL template for accessing uploaded files. Use {key} as placeholder for the file key.
		CustomUrl *string `json:"customUrl,omitempty"`

		// EndPoint S3 endpoint URL (without protocol)
		EndPoint string `json:"endPoint"`

		// PathStyle Whether to use path-style URLs
		PathStyle *bool `json:"pathStyle,omitempty"`

		// Port S3 endpoint port
		Port *float32 `json:"port,omitempty"`

		// Region S3 region
		Region string `json:"region"`

		// SecretKey S3 secret key
		SecretKey string `json:"secretKey"`

		// UseSSL Whether to use SSL/TLS
		UseSSL *bool `json:"useSSL,omitempty"`
	} `form:"s3Config,omitempty" json:"s3Config,omitempty"`
	TemplateId    string  `form:"templateId" json:"templateId"`
	ApiKeyMd5     *string `form:"apiKeyMd5,omitempty" json:"apiKeyMd5,omitempty"`
	ApiKeyHashed  *string `form:"apiKeyHashed,omitempty" json:"apiKeyHashed,omitempty"`
	Sign          string  `form:"sign" json:"sign"`
	Modifications *string `form:"modifications,omitempty" json:"modifications,omitempty"`
	Thumbnail     *bool   `form:"thumbnail,omitempty" json:"thumbnail,omitempty"`
}

// GetV1TemplatesSignedurlParamsFormat defines parameters for GetV1TemplatesSignedurl.
type GetV1TemplatesSignedurlParamsFormat string

// PostV1TemplatesCreateImageJSONRequestBody defines body for PostV1TemplatesCreateImage for application/json ContentType.
type PostV1TemplatesCreateImageJSONRequestBody PostV1TemplatesCreateImageJSONBody

// PostV1TemplatesCreateStoredImageJSONRequestBody defines body for PostV1TemplatesCreateStoredImage for application/json ContentType.
type PostV1TemplatesCreateStoredImageJSONRequestBody PostV1TemplatesCreateStoredImageJSONBody
